name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build Dependencies
      run: |
        make -C libft
        make -C ft_printf

    - name: Build Project
      run: make all

    - name: Run Tests
      run: |
        make check || echo "No test target, skipping."

    - name: Clean Up
      run: make clean
